import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="block md:hidden min-h-screen">{children}</div>
        <div className="hidden md:flex min-h-screen items-center justify-center p-8 text-center">
          <div className="max-w-md">
            <h1 className="text-2xl font-semibold">Bu uygulama mobil için tasarlandı</h1>
            <p className="mt-2 text-muted-foreground">
              Şimdilik sadece telefon ekranlarında kullanılabilir. Lütfen bir mobil
              cihazdan ziyaret edin veya tarayıcıyı mobil görünüme alın.
            </p>
          </div>
        </div>
      </body>
    </html>
  );
}
